##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /Nostalgiaand the desire for authenticity 
# location of code, the full url to your github repository
source-code: https://github.com/chris-tea1/Nostalgia-and-the-desire-for-authenticity

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Nostalgia and the Desire for Authenticity 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A response to the abstract of the ephemeral contemporary image through archive and original work
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This collection of work combines family archives, original photography, and sculpture. The work is a response to the abstract of the ephemeral contemporary image. We are heavily influenced by photography. It is both lasting and evanescent, tangible, and immaterial. In the past 30 years alone, how we create, consume, and share photography has changed dramatically, from a medium that was physical and substantial to completely digital and rarely manifested in physical form."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Christy Mitchell

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: MetadataNostalgia

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
